/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int APARENT = 8;
  /** RegularExpression Id. */
  int FPARENT = 9;
  /** RegularExpression Id. */
  int VARDECL = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int PVIRG = 13;
  /** RegularExpression Id. */
  int ATRIB = 14;
  /** RegularExpression Id. */
  int SOUT = 15;
  /** RegularExpression Id. */
  int NUM = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int MATHOP = 18;
  /** RegularExpression Id. */
  int LOGICOP = 19;
  /** RegularExpression Id. */
  int BOOLVALUE = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"newVar\"",
    "\"int\"",
    "\"bool\"",
    "\";\"",
    "\"=\"",
    "\"System.output\"",
    "<NUM>",
    "<ID>",
    "<MATHOP>",
    "<LOGICOP>",
    "<BOOLVALUE>",
  };

}
